### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by cemyurdakul** [nod5/sumatra_highlight_helper#1]
first, thank you for this addon. it's really good and essential feauture.
but there is only H button working others are not works. it's most probably causes of version of pre relise. I'm using 10766 -64 bit. it would nice to if you get compabilty to newest prerelise

**Comment by nod5** [comment]
Thanks. Yes the most recent SumatraPDF prerelease (10766) changed the keyboard shortcuts. I will update sumatra_highlight_helper but am short on time ATM.

Until then sumatra_highlight_helper works well with the previous SumatraPDF prerelease (10740). Not sure if that installer is still online. Here is the exact filename and filehashes from my local copy.
`SumatraPDF-prerelease-10740-install.exe`
md5 `cb6ea6a0c79fe586b889ed1d86b8b6f3`
sha1 `018954e40c30d488cc89fab00d8bb8aea27d61cd`

**Comment by GitHubRulesOK** [comment]
To change the sumatra_highlight_helper.ahk for current SumatraPDF PRe-release version 11044 or later you will need to alter some lines as follows (note nod5 is intending to update the current source file, when he can) I suggest keep current version as "old_helper.ahk" whilst changed is "new_helper.ahk"
```
MINIMUM of CHANGES (others may be needed for consistency, see final comment below)
-  = old number line as is 
+  = line number for new
=  = no change


-41 H = Highlight selected text + autosaves it into pdfname.pdf.smx
+41 A = [A]nnotate selected text + [A]utosaves it into pdfname.pdf.smx

=73  #h::  ;TOGGLE HIGHLIGHTS [Win] + [H] = [H]ide / un[H]ide DO NOTchange line 73 as [Win] + [A] is taken by Windows Notifications


CHANGE

-380  h::  ;AUTOSAVE TO SMX AFTER HIGHLIGHT
+380  a::  ;[A]UTOSAVE TO SMX AFTER [A]NNOTATION

-400 hotkey, h, toggle ;temp disable hotkey so native highlight command works
+400 hotkey, a, toggle ;temp disable hotkey so native highlight command works

-401 send h
+401 send a

-402 hotkey, h, toggle
+402 hotkey, a, toggle

```
After these changes it may be temperamental I need to switch it off and use a to get yellow then restart ahk for red, green and blue but I suspect those issues may have been there in the  previous pre-release

**Comment by sdsaati** [comment]
Thank you guys for this amazing script !

**Comment by nod5** [comment]
H button issue fixed in new version of the app at https://github.com/nod5/HighlightJump
