### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kkkwong** [nod5/sumatra_highlight_helper#2]
Thanks for this script! I am new to autohotkey and I have no programming knowledge. I wonder if it's possible to change the shortcut keys?

E.g. I would prefer the more intuitive keys
R = Highlight selected text with red color
G = Highlight selected text with green color
Y = Highlight selected text with yellow color
Ctrl+R = Remove all highlighting on this pdf page
(Maybe just leave H alone)

I tried a naive "find and replace" approach but somehow it doesn't work perfectly. Thanks in advance.

**Comment by GitHubRulesOK** [comment]
If you change R for red there is a knock on effect as R is used for Refresh here = Reload in SumatraPDF
G = go to 
B = flip a page in book mode

Y = nothing ? so should be possible to use that for Yellow then red then green then blue ?
Ctrl Y is custom zoom so perhaps
Shift Y to remove all ?

**Comment by nod5** [comment]
Improved shortcuts (R for red, G for green, ...) in new version of the app at https://github.com/nod5/HighlightJump
