### ISSUE TITLE
Expansion of new version

### ISSUE THREAD

**Issue by GitHubRulesOK** [nod5/sumatra_highlight_helper#3]
nod5 I have not looked too close under the hood of your script, but am I right the following section gets the cursor position in points in ANY version of SumatraPDF that has Measure enabled ?

146 loop,3 
147  { 
148  	ControlGetText, xpos, SUMATRA_PDF_NOTIFICATION_WINDOW1, A 
149  	if (xpos != "" and InStr(xpos,"pt") != 0 )  ;need pos in pt measure, not mm or in 
150  	 break 
151  	send m 
152  	sleep 30 
153  } 
154  if xpos =  
155  { 
156  send {Esc} ;close notification win 
157  return  

IF SO then Pre-Release may not be needed since if you read MyNotes  you can jump to page 3 section [☺] https://github.com/GitHubRulesOK/MyNotes/blob/master/AppNotes/SumatraPDF/Annotation%20in%20SumatraPDF.pdf
ALL versions respect .SMX and you only need to interface with refreshing that file, just DO NOT tell SumatraPDF to "Save As..." only use [R]ELOAD.
IT is worth considering Pre-release compatibility (use of keys etc.) but if Your "Helper" can run independent of Pre-Release that would be a big jump forward / bonus

1) it would not matter which release Pre or NOT is active, since you could avoid using H or A and for example just trap M since you want it active but don't want the user to change it.
You could allow both PRe-release and your commands to co-exist by "watching" if key A or H is pressed and  IF saveintodocument = false **&** pre-release is active (not sure how you check that) flush its annotation first before responding to M

2) users have requested other features related to say showing comments which your script could possibly help with, although I'm not sure yet how well that may work, however if pre-release is not needed for your script those features could be enabled in ALL versions. May have to change the name to "SumatraPDF Helper" (not just highlight)

**Comment by nod5** [comment]
> gets the cursor position in points in ANY version of SumatraPDF ... you could avoid using H or A and for example just trap M

The problem is that the mouse position is not the same as the text selection rectangle corner positions. 

For example a user would make this selection with a click near "Mr", drag down and release near "could". 

![selection](https://user-images.githubusercontent.com/11015788/44944087-22e4f300-add1-11e8-9c51-c3547d7693aa.png)

If we capture the M control's data at those two click positions how do we transform that into this highlight rect data for the .smx file ?
```
[highlight]
page = 7
rect = 198 150 330 14
color = #ffff60
opacity = 0.8

[highlight]
page = 7
rect = 84 163 444 15
color = #ffff60
opacity = 0.8

[highlight]
page = 7
rect = 84 177 119 15
color = #ffff60
opacity = 0.8
```
I think changes to SumatraPDF code is required, either to make the ctrl+S steps for .smx annotations silent or to expose details on the current selection to external tools like AutoHotkey.

The method you suggest could however perhaps be used as is to work around the "save as" step for simple non-selection rectangle highlights (ctrl+win+click drag).

> other features related to say showing comments which your script could possibly help with

It is easy to add support for the annontation types underline, squiggly and strikeout to sumatra_highlight_helper. we just change `[highlight]` in the .smx to `[underline]` or `[squiggly]` or `[strikeout]`. I'm not sure yet what hotkeys to use for that though.

Text/comment annotations would be great. But it seems that requires changes to SumatraPDF first.

For example see this code position in SumatraPDF where only the four mentioned annotation types are supported
https://github.com/sumatrapdfreader/sumatrapdf/blob/bc01fa1af94d815dfe96840c34f24079fed9e0f0/src/FileModifications.cpp#L74

MuPDF has support for more annotation types. See
https://github.com/sumatrapdfreader/sumatrapdf/blob/bc01fa1af94d815dfe96840c34f24079fed9e0f0/mupdf/source/pdf/pdf-annot.c#L510

Some background links on annotations
https://mupdf.com/docs/manual-mutool-run.html
https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdfmarkreference.pdf

**Comment by GitHubRulesOK** [comment]
I agree it would be either necessary for user to
1) "same as" highlight pen strike the 3 lines independently, most uses will probably shortcut the action to highlighting the block of all 3 lines. IF you are providing your own "helper settings" dialog it could possibly? include a "grid" value (14 in your example ) to be applied for controlling the height of each line (avoiding overlap) but would need an extra  +10 vertical offset to sit well in that area.

2) somehow from the settings file recognise that pre-release is active ( is the AnnotationDefaults [ . before or after # Settings after this line.. then fallback to pre-release methods) 
The first approach is simpler, adding the second involves some work but you've done 90 % already

I am aware the mupdf features exposed are limited in SumatraPDF to just those 4 as discussed years ago and nobody has bothered to expand them since, my thoughts are
1) existing comments are shown for a limited 5 seconds and it may be possible to capture (right click then control C) them and show in a message box.

~~your blue (or any other) "blob" could be used to open message box for notes (I think you suggested adding a line to .smx) perhaps like this
[highlight]
page = 1
rect = 60 80 9 9
color = #C0FFEE
opacity = 0.8
comment = "this is a 9x9 comment"~~
I Sumatra pre-release removes it when saving the file

2) need a mechanism for keeping comments in separate file perhaps referenced to highlight
[comment] page = 1 rect = 60 80 9 9 comment = "this is a 9x9 comment"

3) the most difficult bit is on pdf save, converting those blobs through say a command line script to a comment suitable to be appended for acrobat etc.
several possibilities e.g. mutools

An example mutools input file: 

%%MediaBox 0 0 595 842
%%Font TmRm Times-Roman
%%Image I0 logo/mupdf-simplified-logo.png

% Draw an image.
q
480 0 0 480 50 250 cm
/I0 Do
Q

% Draw a triangle.
q
1 0 0 rg
50 50 m
100 200 l
200 50 l
f
Q

% Show some text.
q
0 0 1 rg
BT /TmRm 24 Tf 60 762 Td (this is a 9x9 comment) Tj ET
Q

It may be even simpler using coherent command line tool (but not tested that)
 cpdf -add-text "this is a 9x9 comment" -color "0.8 1.0 0.9" -pos-left "60 762" in.pdf [page#] -o out.pdf

note Sumatra uses top left as 0 where as PDF uses bottom left so 762 =842 - 80, at the moment this would just be plain text but there must be a way to convert and attach as floating comment

**Comment by nod5** [comment]
> "same as" highlight pen strike the 3 lines independently, most uses will probably shortcut the action to highlighting the block of all 3 lines. IF you are providing your own "helper settings" dialog it could possibly? include a "grid" value (14 in your example ) to be applied for controlling the height of each line (avoiding overlap) but would need an extra +10 vertical offset to sit well in that area.

One pdf can contain text with different heights for footnotes, headings and so on. How to detect what height to use for a particular highlight? Drawing each text line highlight as a rectangle manually would be too much manual work for the user.

> comment  ... Sumatra pre-release removes it when saving the file

We *can* add persistent comments in .smx files with `# comment text` I think.

So we could make a hotkey to add/show a comment:
- On hotkey press we read mouse position (in pt unit grid) and add a small colored rectangle annotation to the .smx, then prompt the user for text input and store it on a line starting with `#` at the end of rectangle's .smx section.
- On mouse click we read mouse position (in pt unit grid), check if the page and position match any rectangle and, if yes, display the comment text in a popup.

But for that to work neatly SumatraPDF must be updated to expose the mouse position data (in pt unit) without having to use the keyboard shortcut M to show and read the small popup in the left corner.

I will look more into how mutools might be useful. cpdf is unfortunately not FOSS.

**Comment by GitHubRulesOK** [comment]
Some of these changes may take time however if your first task was to separate helper from **relying** on pre-release H or A the others can come later, at present you could simply alter A to work with current pre-release as intended (rev 1.5) , but avoid keys that could interfere with proposed new functionality (rev 2.0)

the suggestion for a grid value is thus not needed now I would simply round to the nearest 1 unit, just let the user decide where blocks across lines go, same as mouse and A, nothing much gained yet  , but nothing lost either (slightly granular positioning), however to have it work in blocks in standard release is a deal breaker.

kjk is working on some updates (current latest commit is related to api  but I would not presume he will prioritise exposing M dialog), hence my question/suggestion  can you force and HOLD M display since to some users it is only a minor inconvenience and others like me its a bonus to have it always visible.

cpdf as you say is "community" so individual user would  need to decide if they qualify (most except corporate would) it is not the only way to go just an example.
