### ISSUE TITLE
Latest Pre-release and SaveIntoDocument

### ISSUE THREAD

**Issue by tuljmdev** [nod5/sumatra_highlight_helper#4]
After completing Setup Step 2 on fresh Sumatra PDF Pre-Release install today: 
```
2. Settings > Advanced Options > SaveIntoDocument = false   
   Settings > Advanced Options > FullPathInTitle = true   
   (All needed for the script to work.)  
```
My Advanced Options state at the bottom:
```
# Settings after this line have not been recognized by the current version
SaveIntoDocument = false
```
FullPath option change took effect and was a value change on a currently existing option. SaveInto option change appears to be rejected after needing to be manually added. Highlighting function inop.

**Comment by GitHubRulesOK** [comment]
@nod5 There have been recent changes that make Auto saving annotations much easier by using Context key and S, however this issue as described suggests that the pre-release in question was not being used (possibly as a result of a dual install ?)
Current pre-release with modified code works well but it would be fantasic if you modify it to work with standard release by changing the code to read cursor AREA and write direct to smx the same way I can easily in standard release use O to write blue blobs

**Comment by nod5** [comment]
@GitHubRulesOK Thanks for notifying.

I will shortly update sumatra_highlight_helper to work with the A key for annotation and the new improved .smx saving method in recent SumatraPDF prereleases.

I won't at the moment add any draw-area-highlight feature for SumatraPDF regular version.

**Comment by GitHubRulesOK** [comment]
@nod5 you have all the skill and code for making what everyone is asks for 
Highlight an area and add a note-let

**Using area in smx avoids the need for pre-release** to select text and using your blue blob approach they just like comments could open a notepad window based on your jotter app FileNoter

"A note file is created with the same name as the clicked file but a .txt extension"

**Comment by nod5** [comment]
Improved method to save .smx file in new version of the app at https://github.com/nod5/HighlightJump
